version: "3.9"

services:
  web:
    build: .
    ports:
      - "4568:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectiot

volumes:
  postgres_data: