# Generated by Django 3.0.8 on 2023-07-19 08:52

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('4135c8a0-f0fc-4b50-95e4-ad70d28cac5e'), editable=False, primary_key=True, serialize=False)),
                ('salle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
