# Generated by Django 3.0.8 on 2023-07-19 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230719_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3ed3b35-b7c5-4b60-8bf6-fda81b5fcc3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
